name: Publish

on: push
# on:
#   push:
#     branches:
#       - 'releases/protos/**'

jobs:
  generate_docs:
    name: Generate docs using protoc-gen-doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run protoc-gen-doc
        working-directory: protos
        run: bash ./scripts/generateDocs.sh
