import { Injectable } from '@nestjs/common'
import { CoreService } from '../core/core.service'
import { SystemService } from '../system/system.service'
import { StatusResponse } from '@hoprnet/hopr-protos/node/status_pb'
import { VersionResponse } from '@hoprnet/hopr-protos/node/version_pb'
import { ShutdownResponse } from '@hoprnet/hopr-protos/node/shutdown_pb'

@Injectable()
export class GrpcService {
  constructor(private coreService: CoreService, private systemService: SystemService) {}

  async getStatus(): Promise<StatusResponse.AsObject> {
    const [coreStatus, systemInfo] = await Promise.all([
      this.coreService.getStatus(),
      this.systemService.getSystemInfo(),
    ])

    return {
      id: coreStatus.id,
      // @TODO: currently types generated by protoc are incompatible
      // @ts-ignore
      multiAddresses: coreStatus.multiAddresses,
      connectedNodes: coreStatus.connectedNodes,
      cpuUsage: systemInfo.cpuUsage,
    }
  }

  async getVersion(): Promise<VersionResponse.AsObject> {
    // @ts-ignore
    return this.systemService.getVersions().then((res) => ({
      version: res.hoprServer,
      componentsVersion: [
        ['@hoprnet/hopr-core', res.hoprCore],
        ['@hoprnet/hopr-core-connector-interface', res.hoprCoreConnectorInterface],
        ['@hoprnet/hopr-core-ethereum', res.hoprCoreEthereum],
        ['@hoprnet/hopr-utils', res.hoprUtils],
        ['@hoprnet/hopr-core-connector-interface', res.hoprCoreConnectorInterface],
      ],
    }))
  }

  async shutdown(): Promise<ShutdownResponse.AsObject> {
    return this.coreService.stop()
  }
}
