import { Injectable } from '@nestjs/common'
import { CoreService } from '../core/core.service'
import { SystemService } from '../system/system.service'
import { StatusResponse } from '@hoprnet/hopr-protos/node/status_pb'
import { VersionResponse } from '@hoprnet/hopr-protos/node/version_pb'
import { ShutdownResponse } from '@hoprnet/hopr-protos/node/shutdown_pb'

@Injectable()
export class GrpcService {
  constructor(private coreService: CoreService, private systemService: SystemService) {}

  async getStatus(): Promise<StatusResponse.AsObject> {
    // @TODO: currently types generated by protoc are incompatible
    // @ts-ignore
    return this.coreService.getStatus().then((res) => ({
      id: res.id,
      multiAddresses: res.multiAddresses,
      connectedNodes: res.connectedNodes,
      cpuUsage: 0, // @TODO: create a service for monitoring the node
    }))
  }

  async getVersion(): Promise<VersionResponse.AsObject> {
    // @ts-ignore
    return this.systemService.getVersions().then((res) => ({
      version: res.hoprServer,
      componentsVersion: [
        ['@hoprnet/hopr-core', res.hoprCore],
        ['@hoprnet/hopr-core-connector-interface', res.hoprCoreConnectorInterface],
        ['@hoprnet/hopr-core-ethereum', res.hoprCoreEthereum],
        ['@hoprnet/hopr-utils', res.hoprUtils],
        ['@hoprnet/hopr-core-connector-interface', res.hoprCoreConnectorInterface],
      ],
    }))
  }

  async shutdown(): Promise<ShutdownResponse.AsObject> {
    return this.coreService.stop()
  }
}
