name: Node.js CI

on:
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.9.1]
        yarn-version: [1.19.2]

    steps:
      # Checkout, Cache and Setup Steps
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Building and testing library
      - name: Install node modules
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          yarn policies set-version ${{ matrix.yarn-version }}
          yarn install --frozen-lockfile
      - name: Build library
        run: |
          yarn policies set-version ${{ matrix.yarn-version }}
          yarn build
      - name: Test library
        run: |
          yarn policies set-version ${{ matrix.yarn-version }}
          yarn test
