name: Node.js CI

on:
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.9.1]
        yarn-version: [1.19.2]
        repository: ['', 'chat', 'protos', 'server']

    steps:
      # Checkout, Cache, Setup Filter and Steps
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            core:
              - '**/*'
              - '!chat'
              - '!protos'
              - '!server'
            chat:
              - 'chat/**/*'
            protos:
              - 'protos/**/*'
            server:
              - 'server/**/*'
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles(format('{0}/{1}', matrix.repository, 'package.json')) }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Building and testing library
      - name: Install node modules
        working-directory: ${{ matrix.repository }}
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          yarn policies set-version ${{ matrix.yarn-version }}
          yarn install --frozen-lockfile
      - name: Build library
        working-directory: ${{ matrix.repository }}
        run: |
          yarn policies set-version ${{ matrix.yarn-version }}
          yarn build
      - name: Test library
        working-directory: ${{ matrix.repository }}
        run: |
          yarn policies set-version ${{ matrix.yarn-version }}
          yarn test
